# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
    - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
    - add_ssh_keys:
        fingerprints:
        - "ab:67:18:77:69:73:28:3b:19:c5:de:00:26:41:ec:7b"

    - deploy:
        name: digital-ocean
        command: ssh -o "StrictHostKeyChecking no" dev@partymaker.zp.ua "cd ~/partymaker-web; ./build.sh"

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master
