export default {
  SET_ENTITIES: 'SET_ENTITIES',

  LOAD_PLACE: 'LOAD_PLACE',
  LOAD_PLACE_FULFILLED: 'LOAD_PLACE_FULFILLED',

  LOAD_ENTERTAINMENTS:  'LOAD_ENTERTAINMENTS',
  LOAD_ENTERTAINMENTS_FULFILLED:  'LOAD_ENTERTAINMENTS_FULFILLED',

  LOAD_ENTERTAINMENT:  'LOAD_ENTERTAINMENT',
  LOAD_ENTERTAINMENT_FULFILLED:  'LOAD_ENTERTAINMENT_FULFILLED',

  CREATE_ENTERTAINMENT:  'CREATE_ENTERTAINMENT',
  CREATE_ENTERTAINMENT_FULFILLED:  'CREATE_ENTERTAINMENT_FULFILLED',

  UPDATE_ENTERTAINMENT:  'UPDATE_ENTERTAINMENT',
  UPDATE_ENTERTAINMENT_FULFILLED:  'UPDATE_ENTERTAINMENT_FULFILLED',
}
