export entertainmentShape from './entertainment'
export placeShape from './place'
export photoShape from './photo'
export contactShape from './contact'
export priceShape from './price'
export additionalServiceShape from './additionalService'
export requirementsShape from './requirements'
